#GitHub defaults
safe: true
lsi: false
pygments: true

exclude:  [ Gemfile, Gemfile.lock, CNAME, LICENSE, README.md]

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

permalink: /post/:title

gravatar:
  hash: d8fdd0359f09e0e006162ff65e0d2c0a

disqus:
  shortname: chaoswalkernet

linkedin:
  apiKey: 77sanow9o08yir
  id: _gb_4QPpWJ

baseurl: http://chaoswalker.net
navigation:
  - text: Posts
    url: /post/
  - text: Curriculum vitae
    url: /resume/
