#GitHub defaults
safe: true
lsi: false
pygments: true

exclude:  [ Gemfile, Gemfile.lock, CNAME, LICENSE, README.md]

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

permalink: /blog/:title 